- news/2015-03-13-Offline-CLI.adoc
Sorry, I've been unable to build the site to see what this looks like, so I really have no clue. I copied formatting patterns I saw on other similar pages and crossed my fingers.
CAUTION: this blog is written as if WildFly 9 Beta1 exists. So it shouldn't be published until that is the case!
> Offline CLI blog

- swarm/index.adoc
Going to throw enough PRs at you that maybe @kenfinnigan and I can get perms to push the site. :)
> First shot at some WF-Swarm web-presence.

- _partials/nav.html.haml
- _partials/projectfooter.html.haml
- swarm/index.adoc
Add WildFly Swarm links to top and bottom navs.
> Fix formatting.

- swarm/index.adoc
Just corrected a small typo on Swarm's index page
> Corrected typo

- news/2015-06-17-WildFly-Swarm-Alpha3-Released.adoc
- news/2015-06-18-WildFly-Swarm-Alpha3-Released.adoc
Blogpost about the release of WildFly-Swarm 1.0.0.Alpha3
> Alpha3 blog

- swarm/fractions.adoc
No need to publish just yet, but I'll file PRs as we find issues.
> Fix a typo.

- news/2015-08-09-WildFly10-Beta1-Released.adoc
Minor change to link to the Javascript support article, from the WildFly 10.0.0.Beta1 release notes
> Link to the article on Javascript hot reloading support, from the release notes

- news/2015-08-19-WildFly-Swarm-Alpha4-Released.adoc
Blogpost for WildFly Swarm 1.0.0.Alpha4 release.
> Alpha4 blog

- .gitignore
- Gemfile
- Gemfile.lock
@n1hility btw are you still on a mac? this fixes the therubytracer/libv8 compilation problem on os x.
> Therubyracer update

- news/2017-05-05-WildFly-CI.adoc
@ctomc : The comparison gets out of whack halfway through due to a line break I added. I really didn't change as much as it appears. Let me know if there are changes I made that you don't like and I will make adjustments.
> Minor edits to WildFly CI news article dated 2017-05-05

- _config/authors.yml
- _ext/authors_helper.rb
- _ext/pipeline.rb
- _ext/tweet_helper.rb
- _layouts/blog.html.haml
I wasn't sure if everyone would want their Twitter handles shared, but I went ahead and added them. I can remove any if wanted.
This just adds an easy way to share a blog post on Twitter for each blog/news entry.
> Add Tweet button to each blog post to easily share on Twitter.

- governance.html.haml
> Issue #102 Update governance page to reflect quarterly release cycle

- _config/releases.yml
- _partials/projectfooter.html.haml
- gethelp.html.haml
- governance.html.haml
- joinus.html.haml
- news/2014-02-06-GlassFish-to-WildFly-migration.adoc
- news/2015-07-02-WildFly9-Final-Released.adoc
- news/2015-07-23-WildFly-901-and-821.adoc
- news/2015-10-26-WildFly902-Released.adoc
- news/2016-01-29-WildFly10-Released.adoc
- news/2016-08-19-WildFly10-1-Released.adoc
- news/2017-08-03-WildFly11-Beta-Released.adoc
- news/2017-08-25-WildFly11-CR1-Released.adoc
- news/2017-10-03-Messaging-features.adoc
- news/2017-10-23-WildFly11-Final-Released.adoc
- news/2018-02-28-WildFly12-Final-Released.adoc
- news/2018-05-30-WildFly13-Final-Released.adoc
- news/2018-08-30-WildFly14-Final-Released.adoc
- news/2018-12-13-WildFly15-Final-Released.adoc
- news/2019-02-27-WildFly16-Final-Released.adoc
- news/2019-03-09-Onward-to_WildFly-17.adoc
- news/2019-06-10-WildFly17-Final-Released.adoc
- news/2019-07-07-WildFly-1701-Released.adoc
- news/2019-10-03-WildFly18-Final-Released.adoc
- news/2019-11-14-WildFly-1801-Released.adoc
- project.properties
This is not a required changed, but was simple enough with a find/replace that I thought I'd just do it.
> Change all instances of issues.jboss.org to issues.redhat.com.

- news/2019-12-17-Ship-your-WildFly-additions-via-Galleon-feature-packs.adoc
Add a link to the snapshot of the example repository
> Reference template repository snapshot

- _partials/nav.html.haml
- _partials/projectfooter.html.haml
https://issues.redhat.com/browse/WFLY-12934
> [WFLY-12934] Remove google+ links

- news/WildFly-s2i-19-released.adoc
Wildfly s2i 19 news. @bstansberry , @pferraro I am highlighting web-clustering (thanks to a new example) and singleton (thanks to existing quickstart). Could you check the 2 examples? Thank-you.
> WF19 2i news

- news/2020-04-13-How-to-configure-wildfly-s2i-by-cli-operations.adoc
A blog post explaining how to use the WildFlu build server hooks and extension mechanism to configure the image executing CLI management operations
CC @bstansberry as possible reviewer
> How to execute CLI operations to configure WildFly S2I image

- _config/releases.yml
- news/2020-05-04-WildFly-1910-Released.adoc
> Add the 19.1.0.Final release

- news/2020-06-12-WildFly-s2i-20-Released.adoc
> [#11] Add the WF 20 blog post file

- _posts/2020-09-30-biased-locking-help.adoc
Hold pending some discussion re the thread utilization variations.
> Blog post seeking data re: biased locking

- _layouts/base.html
> Replace google tracking with original tag

- _posts/2020-10-19-bootable-jar-2.0-released.adoc
@bstansberry that is the blog post to announce Bootable JAR 2.0
> Announce WildFly bootable JAR 2.0 Final

- _data/releases.yaml
Fix the 15.0.1 Final Application Server Source Code download links
> Fix the 15.0.1 Final download links

- _layouts/base.html
> Adding <title> tag

- _posts/2020-10-27-wildfly-operator-0.4.1-released.adoc
> Add blog post about WildFly Operator 0.4.1

- _posts/2020-11-03-WildFly-s2i-21-Released.adoc
@bstansberry @jamezp , that is the announcement for WF 21 s2i images. They have been released some weeks ago, but the announcement has not been done.
> WildFly s2i 21

- _posts/2020-08-13-Introducing-the-WildFly-GraphQL-feature-pack.adoc
fixes https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/26
> Fix broken links in GraphQL blog post

- _posts/2020-12-15-bootable-jar-3.0.Beta-Released.adoc
@bstansberry , @jamezp  this blog post advertises 3.0.0.Beta1 release, mainly the dev-watch goal. Thank-you.
> bootable JAR 3.0.0.Beta1

- _posts/2021-02-01-Bootable-jar-jkube-clustering-openshift.adoc
A step-by-step guide about how to build and deploy a Bootable JAR application on OpenShift by using JKube maven plugin
> Bootable JAR and JKube clustering application on OpenShift

- _data/releases.yaml
- _layouts/index.html
Resolves #237 
Also includes a commit to add the 23 Beta1 QS link
> [Issue 237] Add a WildFly Preview download button 

- _posts/2021-03-11-WildFly23-Final-Released.adoc
Reverts wildfly/wildfly.org#246
> Revert "Drop links until fixed in a couple hours"

- _posts/2021-02-01-Bootable-jar-jkube-clustering-openshift.adoc
- _posts/2021-03-12-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
A blog post about how to configure DNS ping protocol for a Bootable Jar cluster application
> Configure a Bootable Jar cluster application to use DNS_PING protocol

- _posts/2021-03-19-bootable-jar-4.0.Final-Released.adoc
@jamezp @bstansberry that is the announcement of Bootable JAR 4.0 plugin.
Thanks.
> Bootable JAR 4.0 announcement

- _posts/2021-03-19-bootable-jar-4.0.Final-Released.adoc
Some tweaks I told @jfdenise I'd do.
> Bootable JAR 4.0 announcement edits

- README.md
Editing wrong URL in README file.
> Issue-1 Editing wrong URL in README file

- _posts/2021-05-05-helm-charts-for-wildfly.adoc
> Add post about Helm Charts for WildFly

- _posts/2021-05-05-helm-charts-for-wildfly.adoc
> Use singular chart in blog title and synopsis

- _posts/2021-03-19-bootable-jar-4.0.Final-Released.adoc
@jamezp @bstansberry 
I am updating an old post to mention that the issue is now solved using latest Keycloak adapter.
> Add a note to advertise that keycloak issue with bootable JAR is solved

- _posts/2021-06-15-change-log-level-wildfly-cloud.adoc
> Add blog about changing logging level of a WildFly application on the Cloud

- _data/releases.yaml
This currently doesn't have the release announcement, which I may (or may not) submit separately.
> WildFly 24.0.0.Final release

- _posts/2021-06-22-WildFly-s2i-24-Released.adoc
@jamezp @jmesnil . WF 24 s2i images announcement.
> Announce S2I images for WildFly 24.0

- _posts/2021-07-01-wildfly-preview-bootable-jar.adoc
> Add blog post about running WildFly Preview with Bootable Jar

- _sass/global.scss
> [#280] Add warning style

- _posts/2021-08-05-WildFly-s2i-2401-Released.adoc
Signed-off-by: Ken Wills <kwills@redhat.com>
> Add news item for WF 24.0.1 images.

- _posts/2021-10-29-wildfly-s2i-v2-overview.adoc
@jamezp @bstansberry , a typo in s2i v2 post. Thank-you.
> Fix typo in s2i v2 post

- _data/releases.yaml
- _posts/2022-01-21-WildFly-2601-Released.adoc
> WildFly 26.0.1.Final release

- _posts/2022-03-29-WildFly-s2i-26-1-Beta1-Released.adoc
@bstansberry @jamezp @darranl , the news for the 26.1 Beta s2i images.
> Announce 26.1 beta s2i images

- _data/releases.yaml
- _posts/2022-04-14-WildFly261-Final-Released.adoc
This is an alternative to #322 that has a paragraph added re SE 18 support.
> WildFly 26.1 Release announcement

- _posts/2022-04-20-WildFly-s2i-v2-Released.adoc
@jmesnil , early PR for the new WildFly Images to get feedbacks. Thank-you. Should be published on monday.
> Announce WildFly cloud new architecture

- _posts/2022-04-26-YAML-configuration-extension.adoc
> YAML configuration extension in WildFly 26.1

- _posts/2022-05-11-datasource-openshift-vlog.adoc
Link to a new Vlog available on the youtube channel
> WildFly Datasource configuration on OpenShift

- _data/releases.yaml
- _layouts/downloads.html
- _layouts/index.html
- _posts/2022-05-12-WildFlyPreview27-Alpha1-Released.adoc
Adds the release announcement on top of #334
> WildFly Preview 27.0.0.Alpha1 release announcement

- _data/authors.yaml
- _posts/2022-06-21-ejb-over-tls.adoc
Adding post for mutual TLS example application
> Securing Jakarta Enterprise Beans with mutual TLS authentication

- _posts/2022-08-05-wildfly-maven-docker.adoc
> Add post about WildFly Docker and new provisioning architecture

- _posts/2022-08-04-wildfly-maven-docker.adoc
> Publish wildfly-maven-docker on Aug-04

- _posts/2022-08-04-wildfly-maven-docker.adoc
I noticed 2 typos while reading the post
> fix typos in wildfly-maven-docker

- _posts/2022-09-14-Remote-dev-watch.adoc
Signed-off-by: Emmanuel Hugonnet <ehugonne@redhat.com>
> Post about using the new dev-watch remote option for development.

- _posts/2022-09-22-Jakarta-EE10-and-WildFly.adoc
Announce WF 27 Alpha5 compatibility with today GA release of EE 10.
> EE 10 and WildFly

- _posts/2022-11-10-wildfly-docker-temurin.adoc
> add posts about WildFly Docker images with Temurin

- _posts/2022-11-10-wildfly-jakartaee.adoc
Signed-off-by: Scott Marlow <smarlow@redhat.com>
Add a blog about contributing to Jakarta EE SPECs for WildFly users.
> Add 2022-11-10-wildfly-jakartaee.adoc

- _posts/2022-11-09-WildFly27-Final-Released.adoc
Update the WF 27 release announcement with some additional info.
> Add mentions of / links to other posts to the cloud section

- _data/releases.yaml
Renders properly and link works.
> Add the WF 27 QS link

- _posts/2022-11-14-git-tips-upstream-repositories-merge-conflicts-vlog.adoc
Video: https://www.youtube.com/watch?v=v5d6x3kT7lU
> Add Git Tips vlog on upstream repos and merge conflicts

- .github/workflows/github-pages.yml
> [Issue_379] Update to actions/checkout@v3

- _posts/2022-12-07-filesystem-realm-integrity-vlog.adoc
Video: https://www.youtube.com/watch?v=Tzd9GTr8kwE
> Add filesystem realm integrity vlog

- _data/projectfooter.yml
@bstansberry As discussed by email! Let me know if you want me to move the link somewhere else on the website (or any other change).
> Add link to Ansible collection for Wildfly

- _posts/2023-03-09-WildFly-Maven-Plugin.adoc
Creating this as a draft as a review would be nice, but it shouldn't be merged until tomorrow.
> Add a blog post about the wildfly-maven-plugin dev goal.

- _posts/2023-04-13-intellij-server-connector.adoc
Good for a post to wildfly.org, IntelliJ tooling for using wildfly and eap.
> blog post: An Introduction to Server Connector for IntelliJ

- _posts/2023-04-25-using-custom-principals-with-elytron.adoc
Adding Elytron blog on using custom principals in WildFly 28
> Using Custom Principals with Elytron

- _data/authors.yaml
- _posts/2023-06-16-deploy-on-kubernetes-with-helm.adoc
This blog should aid ease of use of the Helm Wildfly chart (https://github.com/wildfly/wildfly-charts/[https://github.com/wildfly/wildfly-charts/) to deploy a simple Wildfly application.
> blog post: Deploy on Kubernetes with Helm

- _posts/2023-07-21-remote-ejb-batch.adoc
Original jberet blog post PR: https://github.com/jberet/jberet.github.io/pull/7
target URL: http://jberet.org/remote-ejb-batch/
> blog post: Remote EJB Client for Batch Application

- _layouts/base.html
- _posts/2021-05-05-helm-charts-for-wildfly.adoc
- _posts/2021-06-15-change-log-level-wildfly-cloud.adoc
- _posts/2023-06-16-deploy-on-kubernetes-with-helm.adoc
- _sass/copy.scss
- _sass/global.scss
- assets/css/main.scss
- assets/javascript/copy.js
I also changed the `overflow` to `auto` so that there is no need to display this ugly white borders if the code snippet is fully displayed
> Add code highlighting & clipboard to source listing

- _posts/2023-09-26-Hacktoberfest-2023.adoc
Add WildFly Core project in hacktoberfest article
> Add WildFly Core project in hacktoberfest article

- _posts/2023-09-26-Hacktoberfest-2023.adoc
Adding WildFly GitHub Bot project in the Hacktoberfest article
> Add WildFly GitHub Bot project in hacktoberfest article

- _posts/2023-11-02-filesystem-integrity-elytron-tool.adoc
Wildfly-elytron blog: https://prarthonapaul.github.io/wildfly-elytron/blog/filesystem-integrity-elytron-tool/
> Added a blog post about adding integrity checking to an existing filesystem realm using the elytron tool

- _data/projectfooter.yml
- _includes/header.html
- _layouts/getstarted.html
- _layouts/index.html
- _sass/layouts/getstarted.scss
- assets/css/main.scss
- getstarted.adoc
https://issues.redhat.com/browse/WFLY-18428
Preview: https://hpehl.github.io/wildfly.org/
> WFLY-18428: Add get started page

- _posts/2023-11-15-wildfly-oidc-identity-propagation.adoc
This just links to a post that's been published on the Elytron website.
> Add a guide about identity propagation with OIDC

- _data/authors.yaml
- _posts/2023-11-16-specify-file-audit-log-encoding.adoc
Add a post that links to Elytron blog https://github.com/wildfly-security/wildfly-elytron/pull/2007
> Add a blog post on how to change the default encoding of the audit log file

- _layouts/post.html
> [#482] Fix nil check in post.html

- _data/authors.yaml
- _posts/2023-11-29-distributed-realm-ignore-unavailable-realms.adoc
Blog post on using distributed realm ignore-unavailable-realms attribute in Elytron
> Blog post on using distributed realm ignore-unavailable-realms attribute in Elytron

- _data/authors.yaml
- _data/releases.yaml
- _posts/2023-12-05-WildFly3001-Released.adoc
Adds a minor tweak to #493 to remove the funky avatar in the blog post
> Pull request 493 update

- _posts/2023-12-07-WildFly-Social-Media.adoc
This article will help us to promote the survey which will help enhance the WildFly Community social media experience.
> Shaping the Future of WildFly Community Social Media

- _posts/2023-12-12-securing-wildfly-apps-auth0-openshift.adoc
Closes https://github.com/wildfly/wildfly.org/issues/510
> Add a guide about securing WildFly apps on OpenShift with Auth0

- _posts/2023-12-20-securing-wildfly-apps-auth0-openshift-vlog.adoc
Closes https://github.com/wildfly/wildfly.org/issues/503
> Add a link to a vlog on securing WildFly apps on OpenShift with Auth0

- _posts/2024-01-18-ansible-wildfly.adoc
This is a repost of my previous blog entry on the topic (from a year ago), but updated for 30.0.1.Final (I just changed the version number and the terminal extracts). Alternatively, I can simply update the original post, but it feels a bit weird for a blog. 
Let me know if you have any issue with this!
> Add a tutorial on using Ansible to set up Wildfly 30.0.1.Final

- _config.yml
- _data/guides.yaml
- _data/projectfooter.yml
- _includes/header.html
- _includes/index-guides.html
- _layouts/guide.html
- _layouts/guides.html
- _sass/layouts/guides.scss
- assets/css/main.scss
- getstarted.adoc
- guides/_includes/_attributes.adoc
- guides/_includes/_prerequisites.adoc
- guides/_includes/_proc-configure-keycloak.adoc
- guides/_includes/_proc-follow-build-and-deployment-openshift.adoc
- guides/_includes/_proc-install-or-update-helm.adoc
- guides/_includes/_proc-log-into-openshift-cluster.adoc
- guides/_includes/_proc-start-keycloak-openshift.adoc
- guides/application-logging.adoc
- guides/automate-with-ansible.adoc
- guides/index.md
- guides/security-oidc-auth0-openshift.adoc
- guides/security-oidc-identity-propagation.adoc
- guides/security-oidc-management-console.adoc
- guides/security-oidc-openshift.adoc
- guides/security-saml-openshift.adoc
- guides/template.adoc
- guides/use-microprofile-config.adoc
- guides/use-microprofile-lra.adoc
This PR contains the initial content from @jmesnil to bring guides to wildfly.org. Preview: https://hpehl.github.io/wildfly.org/
Things to be discussed:
- Guides to start with
- Common structure and data across all guides
- Visual representation
> Add guides to wildfly.org

- _posts/2024-01-26-WildFly-Guides.adoc
> Blog post: WildFly guides

- _posts/2024-01-31-whats-new-in-provisioning.adoc
Draft for review , to be merged after after WF31 announcement and the post https://github.com/wildfly/wildfly.org/pull/519 has been merged.
> What's new in provisioning for WildFly 31

- _posts/2024-02-05-testing-with-wildfly-glow.adoc
Draft for review , to be merged after after WF31 announcement and the post https://github.com/wildfly/wildfly.org/pull/519 has been merged.
> Testing with WildFly Glow blog post

- .github/workflows/update_post.yml
The action renames the blog post and creates a commit like: https://github.com/spyrkob/wildfly.org/commit/be3dc9db7d52f8ba67d5b80270d97a61a37d511e
Fixes #483
> [#483] Github action to update blog post date

- .github/workflows/github-pages.yml
> Dependabot updates

- _layouts/conference.html
To take part in the chat, people must subscribe to the WildFly channel in advance.
> [WildFly conference] Add a note about subscribing to the WildFly channel

- .github/workflows/update_post.yml
Reverts wildfly/wildfly.org#550
> Revert "[Issue_549] Have the update_post workflow merge main into the 'update…"

- _posts/2024-02-27-securing-wildfly-apps-using-okta-openshift-vlog.adoc
Closes https://github.com/wildfly/wildfly.org/issues/520
> Add a vlog explaining how to secure a wildfly application using Okta on OpenShift

- _posts/2024-02-28-How-to-contribute-to-WildFly.adoc
Issue: https://github.com/wildfly/wildfly.org/issues/500
> Blog Post: How to contribute to WildFly

- _data/guides.yaml
- guides/security-oidc-okta-openshift.adoc
Issue: https://github.com/wildfly/wildfly.org/issues/508
> Added a guide to demonstrate how to secure a wildfly application using OKTA

- _posts/2024-03-28-glow-intro-openshift-vlog.adoc
A link to a new vlog. The publication date is the 28 of March.
@bstansberry @jamezp FYI.
Thank-you.
> WildFly Glow, deployment to OpenShift vlog

- _data/guides.yaml
Reordering some security related guides and tweaking their descriptions so that they're consistent as discussed here: https://github.com/wildfly/wildfly.org/pull/544#discussion_r1521489606.
> Re-order security related guides to group together similar guides

- _posts/2024-04-07-WildFly32Beta-released.adoc
@darranl Here you go.
*NOTE TO EVERYONE* 
- Please check links, typos etc carefully. I have not. This is essentially a draft, but not filed as one in case I'm luckily perfect.
- I will not be updating this PR as I am traveling. If changes are needed someone will need to fork this branch and send up their own PR.
Please feel free to change this as you wish. This is me providing input to Darran etc.
> WildFly 32 Beta1 release announcement

- getstarted.adoc
PR for #574. To align with the other guides, change the title from "Next Steps" to "What's next?" and add links to the talk and the guides.
> Add more links to the get started page

- _posts/2024-04-25-WildFly32-Released.adoc
Fix issues @scottmarlow noted on his review of https://github.com/wildfly/wildfly/pull/17830 that apply to the 32 release announcement as well.
> [Issue_298] Correct spec listing mistakes identified by @scottmarlow

- _data/guides.yaml
- guides/security-oidc-scope-openshift.adoc
Based on https://prarthonapaul.github.io/wildfly-elytron/blog/elytron-oidc-client-scope/
> Added a guide for Securing a WildFly Application Using OpenID Connect With Additional Scope Values

- _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
Issue: https://github.com/wildfly/wildfly.org/issues/502
> How to Connect with the WildFly Community

- _data/releases.yaml
And remove the WildFly 32.0.0.Beta1 release.
> Add the WildFly 33.0.0.Beta1 release.

- _data/releases.yaml
> [Issue_630] Add missing quickstart links on the downloads page

- _data/guides.yaml
- guides/security-oidc-request-openshift.adoc
https://wildfly-security.github.io/wildfly-elytron/blog/oidc-cient-request/
> Add a use case driven guide on Sending Request Objects as A JWT Using Request Parameters for OIDC

- _data/guides.yaml
- guides/security-credential-store-enc-exp.adoc
- guides/security-credential-store-for-passwords.adoc
SAme content as https://wildfly-security.github.io/wildfly-elytron/blog/credential-store-for-encrypted-expressions/
> add a guide for Using Credential Stores With Encrypted Expressions on WildFly

- _data/guides.yaml
- guides/security-credential-store-client-config.adoc
Same content as https://github.com/wildfly-security/wildfly-elytron/pull/2184
> Add a guide for Using Credential Stores for WildFly Client

- _posts/2024-09-10-ansible-yaml-wildfly.adoc
@bstansberry Let me know what you think about this proposal!
> Add an article on how to use Ansible and the Yaml Config to automate Wildfly's subsystems config.

- _posts/2024-10-28-WildFly-moves-to-SE-17.adoc
> [Issue_679] Announce moving to an SE 17 baseline

- _posts/2024-10-28-WildFly-mini-conference-save-the-date.adoc
Add post on the WildFly Mini Conference.
> Save the Date: WildFly Mini Conference on Nov 20th

- _posts/2024-11-12-WildFly-mini-conference.adoc
This is the PR for the news post about the next WildFly mini conference.
It should be merged right after #686
> WildFly mini conference news post

- _data/conference.yaml
> [Issue_691] Add the mini conference EE 11 talk abstract

- _data/releases.yaml
- _posts/2024-12-12-WildFly35Beta-released.adoc
Draft whilst I add the main announcement.
> Add the download information for WildFly 35 Beta

- _posts/2024-12-16-vertx-subsystem-in-preview.adoc
The vertx subsystem has been integrated to WildFly Preview, it would be good to mention it here as well.
> Add a post about the vertx subsystem in WildFly Preview

- guides/_includes/_attributes.adoc
> [Issue_716] Move jdk-minimal-version from 11 to 17

- _data/releases.yaml
> Fix WildFly 35 release date

- _data/releases.yaml
> Fix release date for WildFLy 35 Beta

- _data/guides.yaml
> [Issue_646] Organize the guide categories

- _posts/2025-01-21-testing-on-docker-with-cube.adoc
> Add blog post: Testing on Docker with Arquillian Cube

- _data/guides.yaml
- _sass/global.scss
- guides/testing-arquillian-junit5.adoc
resolves #636 
This requires https://github.com/wildfly-extras/guides/pull/7.
Note that I wasn't too sure if this should be a blog post, a guide or simple documentation. However, I went with a guide. If anyone disagrees with this please let me know :)
> [636] Add a guide for Arquillian with JUnit 5

- _posts/2025-03-19-WildFly-mini-conference-2025-save-the-date.adoc
Post for upcoming WildFly Mini Conference
> Announcement: WildFly Mini Conference 2025 - Save the Date

- _data/guides.yaml
- guides/prototyping-with-jbang.adoc
> [#765] Guide for Prototyping with JBang

- _posts/2025-04-25-WildFly-Commonhaus.adoc
I put a hold label on this as I believe Commonhaus may have their own announcement next week and I'll match their timing. But reviews are welcome.
> Commonhaus announcement blog

- _posts/2025-05-05-Exposing-WASM-binaries-as-MCP-tools.adoc
> Adding a new blog entry on defining WASM binaries and how to expose them

- _data/contributors.yaml
I'm adding my GPG info into general contributors document.
> Adding honza-kasik GPG signing info

- content/guides/database-integrating-with-postgresql.adoc
> [#802] Fix wrong links in Datasources Guide

- src/main/resources/web/app/layouts/events.scss
- templates/layouts/events.html
> Add a section to subscribe to the WF calendar

- content/posts/2025-09-26-Hacktoberfest-2025.adoc
FYI @RanabirChakraborty and @fjuma - I fixed two projects' issues related links.
> Update 2025-09-26-Hacktoberfest-2025.adoc to fix Intersmash and Arquillian Cube labeled issues links
