wildfly/wildfly.org

- .htaccess
- swarm/.htaccess
The wildfly-swarm project now has its own domain at http://wildfly-swarm.io. I'm not sure how the wildfly.org site is served, but it appears to be Apache server. Hopefully the .htaccess files here will suffice. 
~/s/wildfly.org git:master ❯❯❯ telnet wildfly.org 80
Trying 209.132.182.26...
Connected to wildfly.org.
Escape character is '^]'.
GET / HTTP/1.0
HTTP/1.1 200 OK
Date: Tue, 01 Dec 2015 20:52:11 GMT
Server: Apache
Last-Modified: Mon, 29 Jun 2015 18:55:56 GMT
The swarm site is still nascent and needs additional content, but that will come shortly. /cc @bobmcwhirter
> Add .htaccess redirects for wildfly-swarm.

- swarm/fractions.adoc
- swarm/index.adoc
- swarm/maven-plugin.adoc
It appears that `<AllowOverrides>` is `false` for the wildfly.org web server configuration, so .htaccess files are not functional. Until that's possible, these changes will redirect browsers to http://wildfly-swarm.io for pages under http://wildfly.org/swarm. /cc @bobmcwhirter
> Add meta refresh and window.location.assign() to swarm pages

- joinus.html.haml
I read this page today and it seemed a bit out of date.
> Links to Core and HipChat, drop IRC refs

- news/2019-06-10-WildFly17-Final-Released.adoc
Release blog  post for WF 17 has a copy-and-paste error use of WF 16 in one spot.
> Fix the WF version number

- news/Custom-Logging-Filter.adoc
Note that I did not prefix the date on the file name due to https://github.com/awestruct/awestruct/issues/547. If the date is added the file path ends up being `2020/01/03/2020-01-03-Custom-Logging-Filter` instead of `2020/01/03/Custom-Logging-Filter`. While this isn't a huge issue if we Awestruct issue gets fixed and we ever upgrade we could end up with broken links. If we'd rather have the year prefix on the file name I can refactor to add it easily.
> Add blog about custom log filters.

- _config/releases.yml
Added WildFly 19.0.0.Beta1 and removed previous betas we no longer want to advertise downloads for.
> Update the downloads page

- _partials/projectfooter.html.haml
- _partials/rightcol-downloads.html.haml
- gethelp.html.haml
- joinus.html.haml
- news/2014-02-06-GlassFish-to-WildFly-migration.adoc
- project.properties
I noticed a couple spaces pointing to the old documentation links so those were updated or removed where there was not a good replacement for them. Specifically these were config links, which I don't think is needed, and extending WildFly, which again I think is okay to lose.
The other commit is for changing the forum links to Google Groups.
Note I'm not sure if the `project.properties` is used, but I changed those as well in case they are.
I've updated the staging site, https://wildfly.org/staging/, so it can easily be checked before this PR is merged.
> Community Space and Docs Updates

- _layouts/base.html
The new site is using the beta site tracking tag. I've replaced it with the original tag so the google analytics will continue in its' historic location. This allows us to have historical data.
Beta Site Analytics (incorrect):
UA-125236544-1
Original Analytics (correct for historical data):
UA-40221748-1
> Replace google tracking with original tag

- _posts/2021-01-15-bootable-jar-3.0.Final-Released.adoc
@bstansberry @jamezp , This the Bootable JAR 3.0 announcement. The date has been set to tomorrow (15th of january).
Thank-you.
> Bootable JAR 3.0 announcement

- _data/releases.yaml
> [#239] Serve WildFly downloads by HTTPS instead of HTTP

- Gemfile
- Gemfile.lock
- _data/releases.yaml
- _posts/2021-06-04-WildFly24-Beta-Released.adoc
Supersedes https://github.com/wildfly/wildfly.org/pull/265
Minor corrections to download versions and also add webrick as missing when using Ruby 3.
> WildFly 24 Beta1 release announcement

- _posts/2021-07-13-helm-chart-with-openshift-dev-console.adoc
With OCP 4.8, the upgrade bug is fixed.
I've update the instructions and moved the workaround to a warning note.
> Update Helm Charts for OpenShift Dev Console

- _data/releases.yaml
- _layouts/downloads.html
I noticed that above every release we have the word "Final" even for the Beta releases.  
This allows an additional "qualifier" to be optionally defined.  I have only needed to add the "qualifier" to the most recent Beta as older Betas are removed - we could use a different qualifier for the micros if we wanted to flag them as "Maintenance".
> Add a release qualifier for releases.

- _posts/2021-09-23-WildFly-s2i-25Beta1-Released.adoc
@darranl @bstansberry The WF25 beta1 blog post announcement. 
NB: We are lightly impacted by the removal of security subsystem, the launch scripts to configure legacy security thanks to env variables has never been integrated in wildfly-s2i, elytron was already the way to go.
Thank-you.
> WildFly 25 beta S2I images announcement

- _data/authors.yaml
- _includes/news-list-blocks.html
- _layouts/news.html
- _posts/2022-04-04-build-deploy-wildfly-quickstarts-openshift.adoc
- _posts/2022-04-04-introducing-wildfly-as-youtube-channel.adoc
- _posts/2022-04-04-securing-wildfly-apps-oidc-openshift.adoc
We made a similar change to the Elytron website as well so we can link to vlogs in addition to blog posts. Here's what it looks like there:
https://wildfly-security.github.io/wildfly-elytron/blog/
> Add special handling for posts that link to vlogs and add posts that link to the three vlogs on the WildFly YouTube channel

- _data/authors.yaml
- _posts/2022-04-22-bootable-jar-new-example-persistent-clustered-ejb-timers.adoc
Hi Team!
After providing a [new example](https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/main/examples/ejb-persistent-clustered-timers) for the Bootable JAR plugin project, I decided to submit this pull request for an WildFly.org blog article that explains it, i.e. shows a common use case for persistent EJB timers in Bootable JARs in clustered contexts.
CC @jfdenise
> Announce new Bootable JAR persistent clustered EJB timers example

- _layouts/base.html
- _sass/global.scss
- _sass/includes/header.scss
- about.md
- assets/css/main.scss
- downloads.md
Builds on #338 by adding context to  a couple page titles
> Use more descriptive page titles for the 'About' and 'Downloads' pages

- _config.yml
- _layouts/downloads.html
- _layouts/index.html
This changes the current release from 26.1.3.Final to 27.0.1.Final. Also introduces a new configuration parameter to easily adjust this. For example on the next release we'd make the `current_release_index: 0` for the latest release.
> Add an option to override the current releases index.

- _layouts/downloads.html
- _sass/layouts/downloads.scss
This results in a link like https://wildfly.org/downloads#27.0.1.Final link to the 27.0.1.Final download row.
Also adds a hover link to the version id.
> Add links anchor links to download versions.

- _data/authors.yaml
- _posts/2023-06-26-Client-cert-auth-without-roles.adoc
Wildfly-elytron blog: https://wildfly-security.github.io/wildfly-elytron/blog/Client-cert-auth-without-roles/
WildFly-elytron blog Pull Request: https://github.com/wildfly-security/wildfly-elytron/pull/1913
> Add example for using Certificate Based Authentication with Mutual TLS without roles 

- _layouts/base.html
Testing to see if the system will work will referencing the JS file off of a RH server.
> Change location of javascript.

- _sass/colors.scss
This color is less bright for code listing
> Desaturate the yellow from the color palette

- _layouts/post.html
- _sass/global.scss
Fixes #363 
Article with one author with an avatar image:
Article with multiple author, all with avatar image:
Default image when one of authors doesn't have an avatar:
> [#383] Add author picture to the blog post

- _includes/news-list-blocks.html
This PR brings back the author names in the news section on the homepage
> Fix missing authros in news section on home page

- _layouts/getstarted.html
- getstarted.adoc
This PR adds a link to the OpenShift guide to the getting started page as discussed in https://issues.redhat.com/browse/EAPENGOKR-94?focusedId=23773952&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23773952
The links should actually be part of the content in `geststarted.adoc`, but I always want to link to the *latest* guide. So I decided to move the links to the layout. If there's a better approach, please let me know.
> Add a link to the OS guide on the getting started page

- _posts/2024-01-31-WildFly-mini-conference.adoc
This is the PR for the news post about our WildFly mini conference. 
I've kept it pretty short and only listed the most important facts. Everything else can be found on the conference page itself. But I appreciate any suggestions to make it more detailed.
I'm not sure exactly when the news post is supposed to go online. I guess right after the conference page itself is published. In that case, we would have to adjust the name and date of the news post.
> WildFly mini conference news post

- .github/workflows/update_post.yml
Fixes #536
Use the commit message in format: "Update ${OLD_BLOG_FILENAME} blog date" as PR title.
> [#536] update_post action - use the commit message to create PR title

- guides/application-logging.adoc
This is a replacement for #541
One thing to note, and please let me know if I need to change it back, was the Maven Plugin configuration did not look quite right to me. However, I don't know what example application we're referencing.
It's also made me realize we might want to look at how we handle CLI commands for the various goals. Currently with we do not support executing commands in the `provision` goal, but maybe we should. That is the reason I added the executions to execute the `provision` and `execute-commands` goals.
> Update the logging guide.

- _layouts/news.html
Fixes https://github.com/wildfly/wildfly.org/issues/564
It turned out that it didn't require a major Jekyll surgery. My solution is to hide the button (using CSS [visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility)) if it isn't necessary.
> Make the 'Older Posts' button stick to the bottom right

- _posts/2024-05-06-caching-realm-update-of-credentials.adoc
Based on: https://wildfly-security.github.io/wildfly-elytron/blog/caching-security-realm-authenticate-with-underlying-realm-on-failure/
> Add a blog on how caching realm can now update obsolete credentials

- _layouts/base.html
- assets/javascript/tracking.js
The Matomo POC has run it's course and is being sunset. I've removed the associated code from the Wildfly site. We're currently trying to have in internal instance of Matomo that is fully supported. I'll reach out once we get it up and running.
> Matomo POC closing, remove code

- _layouts/index.html
- _layouts/releases.html
- releases.md
The /releases page lists the Release announcements from WildFly (based on the tags "release announcement") to provide a one-page destination for all WildFly releases.
This fixes #611
> [#611] Add a /releases page

- _data/guides.yaml
- guides/security-credential-store-for-passwords.adoc
This guide has the same content as https://wildfly-security.github.io/wildfly-elytron/blog/credential-store-for-passwords/
> Add a guide on Using Credential Stores to Replace Clear Text Passwords in WildFly

- _data/guides.yaml
- guides/database-integrating-with-postgresql.adoc
> [#577] Guide: Integrating with a PostgreSQL database

- guides/get-started-microservices-on-kubernetes.adoc
When running locally with:
```shell
bundle exec jekyll serve
```
the resulting urls for links on page https://www.wildfly.org/guides/get-started-microservices-on-kubernetes are like:
http://127.0.0.1:4000/guides/get-started-microservices-on-kubernetes/simple-microservice-part1
but when looking at the deployed site the ulrs are missing the `get-started-microservices-on-kubernetes` token and the user gets:
```html
Error '404'
ERROR FOUR O’ FOUR
LOST IN THE WildFly MOUNTAINS
YOU SHOULD TRY THE NAV
```
> Fix links on get-started-microservices-on-kubernetes.adoc

- guides/get-started-microservices-on-kubernetes.adoc
Follows up on https://github.com/wildfly/wildfly.org/pull/650
This just removes the `{{site.baseurl}}` because this has no configuration value at `_config.yml `, instead use direct absolute paths from root.
> Remove site.baseurl variables from adoc since it has no configruation

- _posts/2024-10-10-jakarta-data.adoc
> [Issue_668] Jakarta Data blog post

- _posts/2024-10-28-WildFly-mini-conference-save-the-date.adoc
Also remove colon in the jekyll front matter description value; it seems to be an illegal character
See https://github.com/wildfly/wildfly.org/pull/678#discussion_r1824285639
> Fix url in 2024-10-28-WildFly-mini-conference-save-the-date.adoc

- _data/releases.yaml
The url doesn't follow the normal pattern, but the url has been tweeted, so I think it prudent to break the "norm" rather than an untold number of shares.
> Fix release notes link

- _config.yml
- _includes/teaser.html
- _layouts/index.html
This PR redefines whether and how a teaser is visible on the home page: 
- The flag `show_teaser` in `_config.yml` controls the visibility of the teaser. 
- The include `_includes/teaser.html` defines the content of the teaser.  
For future teasers it's no longer necessary to edit the homepage, define the content in `_includes/teaser.html` and adjust `show_teaser` in `_config.yml`.
> Add 'show_teaser' flag and 'teaser.html' include

- _posts/2025-02-19-testing-on-k8s-with-cube.adoc
> Blog post: Testing on Kubernetes with Arquillian Cube

- _data/guides.yaml
- _includes/index-guides.html
This PR moves the "WildFly mini Series" index up one level into the "Guides" page by creating a new "Docker and Kubernetes" category:
"Draft" because this MR is based upon https://github.com/wildfly/wildfly.org/pull/671 and has to be re-based & merged afterwards
> New "Cloud and Containers" category in Guides

- _data/conference/202503.yaml
This PR adds the links to the topics in the WildFly Zulip chat on the WMC 03/2025 agenda page.
> Add Zulip chat links for the WMC 03/2025

- guides/get-started-microservices-on-kubernetes/simple-microservice-part1.adoc
This change is to be merged when https://github.com/wildfly/wildfly-archetypes/issues/145 is merged and a new release of the wildfly archetype has been done.
> Use WildFly Glow support for simple-microservice-part1.adoc guide

- _data/releases.yaml
- _layouts/contributors-pgp.html
- _layouts/downloads.html
- _posts/2025-06-26-WildFly37Beta-released.adoc
Also include links to the .asc files to enable verification of the signatures.
Finally publish the ID of the key used to sign the release as different people will use their own GPG key when releasing.
> Add the download information for WildFly 37 Beta
